export type Category = {
  id: string;
  name: string;
  slug: string;
  order: number | null;
  is_active: boolean;
  image_url: string | null;
  rappi_url: string | null;
  pedidosya_url: string | null;
  color_hex: string | null;
  text_color: string | null;
};

export type Product = {
  id: string;
  category_id: string | null;
  name: string;
  slug: string;
  description: string | null;
  price_display: string | null;
  price_amount: number | string | null;
  discount_percent: number | string | null;
  image_url: string | null;
  rappi_url: string | null;
  pedidosya_url: string | null;
  order: number | null;
  is_active: boolean;
};

export type LegalPage = {
  id: string;
  slug: string;
  title: string;
  content: string | null;
  updated_at: string | null;
};

export type Reclamacion = {
  id: string;
  numero_hoja: string;
  fecha_registro: string;
  proveedor_nombre_razon_social: string;
  proveedor_ruc: string;
  proveedor_domicilio_establecimiento: string;
  proveedor_codigo_identificacion_establecimiento: string | null;
  consumidor_nombre_completo: string;
  consumidor_domicilio: string;
  consumidor_tipo_doc: string;
  consumidor_num_doc: string;
  consumidor_telefono: string;
  consumidor_email: string;
  consumidor_padre_madre: string | null;
  consumidor_es_menor: boolean;
  bien_tipo: string;
  bien_monto_reclamado: number | string;
  bien_descripcion: string;
  tipo_registro: string;
  detalle_reclamacion: string;
  pedido_consumidor: string;
  acciones_proveedor: string | null;
  acciones_fecha: string | null;
  confirmacion_consumidor: boolean;
  confirmacion_consumidor_fecha: string | null;
  confirmacion_proveedor: boolean;
  confirmacion_proveedor_fecha: string | null;
  estado: string;
  respuesta_proveedor: string | null;
  fecha_respuesta: string | null;
  fecha_comunicacion_respuesta: string | null;
  prorroga_hasta: string | null;
  prorroga_motivo: string | null;
  prorroga_fecha_comunicacion: string | null;
  public_token?: string | null;
  updated_at?: string | null;
};

export type SiteSettings = {
  id: string;
  brand_name: string | null;
  hero_title: string | null;
  hero_subtitle: string | null;
  meta_pixel_id: string | null;
  google_tag_id: string | null;
  rappi_url: string | null;
  pedidosya_url: string | null;
  facebook_url: string | null;
  instagram_url: string | null;
  tiktok_url: string | null;
  whatsapp_url: string | null;
  contact_email: string | null;
  logo_url: string | null;
  favicon_url: string | null;
  footer_logo_url: string | null;
  libro_reclamaciones_logo_url: string | null;
  hero_image_url: string | null;
  top_bar_text: string | null;
  top_bar_bg: string | null;
  top_bar_text_color: string | null;
  header_bg: string | null;
  header_text_color: string | null;
  page_bg: string | null;
  accent_color: string | null;
  accent_text_color: string | null;
  pill_bg: string | null;
  pill_text_color: string | null;
  pill_active_bg: string | null;
  pill_active_text_color: string | null;
  footer_bg: string | null;
  footer_text_color: string | null;
  updated_at: string | null;
};
